name: Astrolaser builf and release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Prebuild.sh
        run: bash .github/workflows/scripts/prebuild.sh

      - name: Build project
        run: |
          godot --headless --path . --export-release "Windows Desktop" game.exe
          zip astrolaser_x64_windows.zip game.exe game.pck

      - name: Upload build artifact windows
        uses: actions/upload-artifact@v3
        with:
          name: astrolaser-artifact-win
          path: astrolaser_x64_windows.zip

  release:
    runs-on: godot
    needs: build
    steps:
      - name: Download build artifact win
        uses: actions/download-artifact@v3
        with:
          name: astrolaser-artifact-win
          path: ./

      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "astrolaser_x64_windows.zip,labyrintum_x64_linux.zip"
          bodyFile: "body.md"
